lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
remote_theme: dieghernan/chulapa
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
include:
  - "001-Introduction to Python.md"