lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
remote_theme: "mmistakes/so-simple-theme@3.2.0"
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
include:
  - "001-Introduction to Python.md"