title: Learn Python with Zartosht
description: >- # this means to ignore newlines until "baseurl:"
  As I learn Python, I will document my journey here. I hope you find it useful.
baseurl: "learning-python"
lsi: false
safe: true
source: .
incremental: false
gist:
  noscript: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
markdown: kramdown
sass:
  sass_dir: _sass